spring.application.name=activities
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/activities_db
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

#Para empezar rápido: crea/actualiza tablas automáticamente
spring.jpa.hibernate.ddl-auto = update
# Buenas prácticas
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Logs SQL (opcional)
spring.jpa.show-sql=true

# JWT Config
jwt.secret=3f6939211b737a2fbb2b54e1303365f58a2bb8174ddf528b0066677240a8f9c0
jwt.expiration-ms=86400000
# 86400000 ms = 24 horas

# CORS (permite peticiones desde el frontend)
spring.web.cors.allowed-origins=http://localhost:5173